# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "stork-plugin"
client_id = "b8ad70fd7823781193947cf9add5877f"
application_url = "https://shots-completed-teach-attachment.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://shots-completed-teach-attachment.trycloudflare.com/auth/callback",
  "https://shots-completed-teach-attachment.trycloudflare.com/auth/shopify/callback",
  "https://shots-completed-teach-attachment.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "stork-app-test.myshopify.com"
