# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "stork-dev"
client_id = "abd04261ccb373ed459a56202f644a69"
application_url = "https://perry-interpreted-wines-identify.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://perry-interpreted-wines-identify.trycloudflare.com/auth/callback",
  "https://perry-interpreted-wines-identify.trycloudflare.com/auth/shopify/callback",
  "https://perry-interpreted-wines-identify.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://eminem-installation-supplier-encyclopedia.trycloudflare.com/api/mandatory/customers/redact"
  customer_data_request_url = "https://eminem-installation-supplier-encyclopedia.trycloudflare.com/api/mandatory/customers/data_request"
  shop_deletion_url = "https://eminem-installation-supplier-encyclopedia.trycloudflare.com/api/mandatory/shop/redact"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "stork-plugin-rework.myshopify.com"
