# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "stork-dev"
client_id = "abd04261ccb373ed459a56202f644a69"
application_url = "https://stork-app.dev-test.pro"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products, write_products, read_orders, write_orders"

[auth]
redirect_urls = [
  "https://stork-app.dev-test.pro/auth/callback",
  "https://stork-app.dev-test.pro/auth/shopify/callback",
  "https://stork-app.dev-test.pro/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "better-carts-dev.myshopify.com"
